adb shell am start -a android.intent.action.VIEW -d "stt://stt.local/task-list/\
new?task=eyJpZCI6ImM1MTU5OTkwLTVlMjEtNDNkNS1hY\
jNjLTM1OTA4NjFmNDUzZiIsInRleHQiOiI1NSIsInByaW9yaXR5IjoyLCJjb21wbGV0ZWQiOmZhbHNl\
LCJjcmVhdGVkQXQiOiIyMDIzLTA3LTAxVDE0OjM0OjQyLjA2MiIsImNoYW5nZWRBdCI6IjIwMjMtMDc\
tMDFUMTQ6MzQ6NTYuMzYyIiwiZGVhZGxpbmUiOjE2ODk2MzEyMDAwMDB9"
